inherits = "catppuccin_mocha"

"ui.background" = { fg = "text" }
"ui.cursorline.primary" = {}
"ui.selection" = { fg = "text" }
"ui.linenr.selected" = {}
"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "text" }
"ui.virtual.inlay-hint" = {}
"ui.menu" = {}
"ui.popup" = {}
