#!/usr/bin/env bash

# This script is generated by Matugen to update Niri's colors live.

if command -v niri >/dev/null && niri msg --help >/dev/null 2>&1; then
    niri msg action focus-ring-active-color "{{colors.primary.default.hex}}"
    niri msg action focus-ring-inactive-color "{{colors.surface_container.default.hex}}"
fi
