# Bindings
bind = SUPER, R, reload_config
bind = SUPER, TAB, toggleoverview

# apps
bind = SUPER,Return,spawn,ghostty
bind = SUPER,E,spawn,neovide
bind = SUPER,M,spawn,ghostty -e meowmux
bind = SUPER+SHIFT, M, spawn, ghostty -e rmpc

# dms bindings
bind = SUPER,Space, spawn, dms ipc call spotlight toggle
bind = SUPER, V, spawn, dms ipc call clipboard toggle
bind = SUPER+CTRL, I, spawn, dms ipc call night toggle
bind = SUPER, Escape, spawn, dms ipc call lock lock
bind = SUPER, N, spawn, dms ipc call notepad toggle


# scratchpad
bind = SUPER, P, toggle_scratchpad
bind = SUPER+SHIFT, P, minimized
bind = SUPER+CTRL, P, restore_minimized

# quitting
bind = SUPER,W, killclient
bind = SUPER+SHIFT, E, quit

# Focus
bind = SUPER,H,focusdir,left
bind = SUPER,L,focusdir,right
axisbind=SUPER,UP,focusdir,left
axisbind=SUPER,DOWN,focusdir,right

# window management
bind = SUPER+SHIFT ,H,exchange_client,left
bind = SUPER+SHIFT,L,exchange_client,right
bind = SUPER+SHIFT,K, tagtoleft
bind = SUPER+SHIFT, J, tagtoright
bind = SUPER+SHIFT, F, togglefullscreen
bind = SUPER, F, togglefloating
bind = SUPER, G, toggleglobal

# mouse
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# tag changing
bind = SUPER,K, viewtoleft
bind = SUPER, J, viewtoright

# Multimedia 
bind = SUPER+CTRL,1,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%-
bind = SUPER+CTRL,2,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%+
axisbind=SUPER+SHIFT,UP,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%+
axisbind=SUPER+SHIFT,DOWN,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%-
bind = SUPER+CTRL,3,spawn,brightnessctl set 5%-
bind = SUPER+CTRL,4,spawn,brightnessctl set 5%+
axisbind=SUPER+CTRL,UP,spawn,brightnessctl set 5%+
axisbind=SUPER+CTRL,DOWN,spawn,brightnessctl set 5%-
bind = SUPER+CTRL,I,spawn,bash -c ~/.config/mango/toggle-nightlight.sh

# Layout switching
bind = SUPER+SHIFT, R, switch_layout
bind = SUPER, S, setlayout, scroller
