# Bindings
bind = SUPER,Return,spawn,ghostty
bind = SUPER,Space,spawn,bash -c ~/.config/rofi/apps.sh
bind = SUPER,Q,spawn,bash -c ~/.config/rofi/wallpaper.sh
bind = SUPER,V,spawn,bash -c ~/.config/rofi/clipboard.sh
bind = SUPER,E,spawn,neovide
bind = SUPER,N,spawn,swaync-client -t
bind = SUPER,Escape,spawn,hyprlock
bind = SUPER,M,spawn,ghostty -e meowmux
bind = SUPER+SHIFT, M, spawn, ghostty -e rmpc
bind = SUPER, R, reload_config
bind = SUPER, P, minimized
bind = SUPER+SHIFT, P, toggle_scratchpad
bind = SUPER+CTRL, P, restore_minimized


bind = SUPER,W, killclient
bind = SUPER+SHIFT, E, quit

# Focus
bind = SUPER,H,focusdir,left
bind = SUPER,L,focusdir,right
axisbind=SUPER,UP,focusdir,left
axisbind=SUPER,DOWN,focusdir,right
bind = SUPER,K, viewtoleft
bind = SUPER, J, viewtoright

# Move
bind = SUPER+SHIFT ,H,exchange_client,left
bind = SUPER+SHIFT,L,exchange_client,right
bind = SUPER+SHIFT,K, tagtoleft
bind = SUPER+SHIFT, J, tagtoright

# Multimedia (matching Niri/Hyprland)
bind = SUPER+CTRL,1,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%-
bind = SUPER+CTRL,2,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%+
axisbind=SUPER+SHIFT,UP,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%+
axisbind=SUPER+SHIFT,DOWN,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 6%-

bind = SUPER+CTRL,3,spawn,brightnessctl set 5%-
bind = SUPER+CTRL,4,spawn,brightnessctl set 5%+
axisbind=SUPER+CTRL,UP,spawn,brightnessctl set 5%+
axisbind=SUPER+CTRL,DOWN,spawn,brightnessctl set 5%-

bind = SUPER+CTRL,I,spawn,bash -c ~/.config/hypr/toggle-nightlight.sh

# Layout switching
bind = SUPER+SHIFT, R, switch_layout
bind = SUPER, S, setlayout, scroller
