# MangoWM Configuration

# Source
source = ~/.config/mango/colors.conf
source = ~/.config/mango/layout.conf
source = ~/.config/mango/visuals.conf
source = ~/.config/mango/bindings.conf

# Startup
exec-once = ~/.config/mango/start-up.sh

