# MangoWM Configuration

# Source
source = ~/.config/mango/colors.conf
source = ~/.config/mango/layout.conf
source = ~/.config/mango/visuals.conf
source = ~/.config/mango/bindings.conf

# Startup
exec-once = ~/.config/mango/start-up.sh

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller

