scroller_structs=20
scroller_default_proportion=1.0
scroller_focus_center=1
scroller_prefer_center=1
scroller_prefer_overspread=0
edge_scroller_pointer_focus=1

enable_hotarea=1
jump_labels=123456789
