# blur
blur = 1
blur_layer = 1
blur_params_radius = 7
blur_params_noise = 0.1
blur_optimized = 1

# border_radius
border_radius = 12

# shadows
shadows=1
layer_shadows=1
shadow_only_floating=0
shadows_size=12
shadows_blur=15
shadows_position_x=0
shadows_position_y=0
shadowscolor=0x000000ff

# opacity
focused_opacity = 0.8
unfocused_opacity = 0.8

# Animations
tag_animation_direction=0
animations = 1
animation_duration_open = 400
animation_duration_close = 400

# border
borderpx = 3

# cursor
cursor_size=24
cursor_theme=Adwaita
