# Visuals
blur = 1
blur_optimized = 1
border_radius = 12


# opacity
focused_opacity = 0.8
unfocused_opacity = 0.8

# Animations
animations = 1
animation_duration_open = 400
animation_duration_close = 400

# border
borderpx = 2

# cursor
cursor_size=24
cursor_theme=Adwaita
